### PR TITLE
feat: custom color support + android custom progress color

### PR DESCRIPTION
**Pull request by 4cc3ssX**
This PR includes the following enhancements:

**feat**: Support for parsing custom colors in various formats including hexadecimal, RGBA, and named colors. The `parseColor` function now can handle these formats, allowing for flexible color customization on both Android and iOS.

**feat(android)**: Custom progress bar color support for Android with `progressColor` prop.

### CODE REVIEW

**Comment by 4cc3ssX** [comment]
Hello @baronha, could you please look at this PR?

**Comment by baronha** [comment]
Yup. Thank you for your efforts. I will take a look at this PR <3

**Comment by 4cc3ssX** [comment]
Hello @baronha, I've also added support `shouldDismissByDrag` for Android.🎉

**Comment by baronha** [comment]
> Hello @baronha, I've also added `shouldDismissByDrag` support for Android.🎉

Wow. It's amazing behavior 🫡🫡🫡

**Comment by 4cc3ssX** [comment]
But still in-progress to adjust the gesture threshold that should exactly same as what `SPIndicator` does.

**Comment by baronha** [comment]
> But still in-progress to adjust the gesture threshold that should exactly same as what `SPIndicator` does.

It probably needs an improvement in the future. I find your efforts great 🔥🔥🔥

**Review by baronha — APPROVED** [review]

**Pull request merged**
